### PR TITLE
Suppress disks with _NP status / Updated Disk shares page

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
For "normal" setup conditions work, but please test whether cache pool is also working.

I have updated the help text of Disk shares file, have a look and see if it matches the help of User shares.

**Comment by limetech** [comment]
Yes works great!  I made a few more changes including adding ability to set the "comments" field for a disk share.  Now on Shares page we have same column headings.

I'll try to get a push back out here to github this evening.  Some of these changes you won't see until you get -rc4 but by tomorrow morning your time hopefully I'll have something for you.

**Comment by bergware** [comment]
I guess it took a bit longer than expected, if you need a sanity check, let me know, no problem to help out.

**Comment by limetech** [comment]
Some issues with special chars in share names, in some page files but also in emhttp.  About got it sorted.

**Pull request merged**
