### PR TITLE
Revert sum (plus) icon to original

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
The icon also algins the text on the last row, alternatively it becomes an "empty" icon

**Comment by limetech** [comment]
Yes, very nice.

**Comment by limetech** [comment]
Another change I want to make is this: with array stopped you should be able to spin down individual HDD's.  This is to handle case were someone wants to remove a drive and replace with another.  It's easier on the device to remove a HDD when it's spun down.

This functionality won't work now unfortunately because somewhere along the way the 'cmdStatus' emhttp operation results in spinning up drives.  I'm tracking this down, so in a future release I'd like to add this spin down capability.

**Comment by bergware** [comment]
In the webGUI it is easier to implement.by removing the check whether the array is started or not.

**Pull request merged**
