### PR TITLE
Update, expand and correct notification system (several files)

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
The above pull request focuses mainly on improvements of the notifications system. A short summary of what has changed.

1. Possibility to specify per notification type what entity (browser or email) should be used
2. Addition of periodic array status check with a selectable interval
3. Possibility to specify the entity for the periodic array check (if enabled)
4. Email only notifications are now also archived
5. The SMTP settings have been adjusted to reflect the above
6. Added USB flash drive read-only notification
7. Added disk read errors notification
8. Possibility to specify which SMART attributes can generate a notification (including highlighting in disk health tab)
9. Corrections in systeminfo (sometimes wrong memory display)
10. Plugin manager, always show release notes when available

**Comment by eschultz** [comment]
@bergware Do you have any other code changes you're working on outside of this pull request?  I've been working on the revamped docker manager and it modifies a few of the core files so I'll need to merge any changes from the master branch and this PR in to my local branch, resolving any conflicts along the way, before I submit my pull request.

**Comment by bergware** [comment]
No further code changes from my side for the webGui at this moment. Waiting for the changes to get merged.

**Comment by limetech** [comment]
Nice work man!

You want to get rid of a separate email recipient list for warning/alert-only email?  I kinda thought this was an interesting feature, though I can see it might have limited utility.

Just one suggestion: I like the idea of "commit early and often":
https://sethrobertson.github.io/GitBestPractices/#commit

After each set of file changes to implement a chunk of work has been made and tested, you commit right then, rather than piling up a whole bunch of logically unrelated changes and then do one big commit.  This makes it easier to see what file changes went into individual feature changes/bug fixes.  Also makes it easier to back out those changes if necessary.   My 2 cents.

**Comment by bergware** [comment]
The email recipient is usually one and the same person, I don't expect a whole NOC team :)

With the new ability to indicate per type of importance what notification to send, the recipient can filter as he wishes. I think it is a better approach, but you may disagree of course.

I am aware that several changes were grouped together (hence the title), usually I do the small and often approach, thanks for reminding!

**Comment by limetech** [comment]
For this particular feature of separate email address for warning/alert only, I agree it probably is safe to remove in interest of simplification, but in general we carefully consider removing features because one never knows how a customer may be using it.  At best, we get no complaints, or someone complains but they are happy to work with it.  At worse we have to put the feature back.

Again, not asking you to put the feature back, just maybe a quick discussion: "Hey this feature looks superfluous, how about we remove it?".

**Comment by bergware** [comment]
Sure will do that, no worries!

**Pull request merged**
