### PR TITLE
Added description text for under *System*

### PR DESCRIPTION
**Pull request by jonpanozzo**
Highlights additional items now included in system diagnostics.

### CODE REVIEW

**Comment by eschultz** [comment]
Nice, I think it's about time to remove your training wheels!  :+1:  

baby-steps

**Comment by limetech** [comment]
Sorry I'm going to have to *fully test* that change before I can merge it :8ball:

**Comment by jonpanozzo** [comment]
Hey....what's this big green button called "Merge pull request" do?

/blinks innocently

**Comment by bergware** [comment]
Great job, all checked :)

all checked

**Comment by limetech** [comment]
Now that Jon has `<br>` mastered, he's moved on to `<p>`.

**Comment by jonpanozzo** [comment]
Sent from Windows Mail





From: tom mortensen
Sent: ‎Thursday‎, ‎July‎ ‎9‎, ‎2015 ‎12‎:‎11‎ ‎PM
To: limetech/dynamix
Cc: jonp@lime-technology.com





Now that Jon has <br> mastered, he's moved on to <p>.

**Comment by bergware** [comment]
This is more to your liking ...

games

**Comment by jonpanozzo** [comment]
Is that your office?

**Pull request merged**
