### PR TITLE
User List: make icons 48x48 and look for custom user icon on flash drive

### PR DESCRIPTION
**Pull request by eschultz**
Referencing #163 - User list modifications:
- Show all user icons as 48x48
- Use custom user icon if found under /boot/config/plugins/dynamix/users/<username>.png
- Description is only shown on mouse hover

### CODE REVIEW

**Comment by eschultz** [comment]
Wanted something easy to do before I put on and zipped up the coding hoodie to tackle the OpenELEC VM template :sunglasses:

**Comment by limetech** [comment]
Careful walking out the door late at night with that coding hoodie on, the GPL police might just assume you're stealing some code....

**Comment by limetech** [comment]
capture

That's what I'm talking about!

**Comment by eschultz** [comment]
Awesome!  Will have to revise the code down the road to randomly swap in
Shemp

**Comment by bergware** [comment]
Haha, fantastic guys !!!

**Comment by limetech** [comment]
And Joe

**Pull request merged**
