### PR TITLE
Support of new cron mechanism

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
I moved the "wrappers" to their own PHP file, and use include to read the file content, this way there is only one 'source' (previously the same routine was copied several times).

The modifications support the creation of the following .cron files:

parity-check.cron : runs scheduled parity check
plugin-check.cron : runs plugin version check and reports anything newly available
status-check.cron : runs regular array health check and reports pass/fail condition

You will need to verify how it fits with the 'mover' modifications.

Also the temporary "band-aid" plugin is not compatible with this approach and needs to be removed BEFORE the upgrade to B14.

**Comment by limetech** [comment]
Reviewing now... very nice work man!  Actually I just produced a "-beta13a" (which is internal pre-release of -beta14) and Jon is testing now.  I will merge these changes and produce a -beta13b for you to check out.  I'll send you link via email when it's ready.

**Comment by bergware** [comment]
I also noticed that updating the cron table takes a while, you want to do this only on request basis - not periodically.

**Comment by limetech** [comment]
That's because 'crontab' command actually generates a file called 'cron.update' which crond looks for once a minute.  This file contains a list of files that specify 'modifications' to the internal cron table maintained by crond.  Hence will take anywhere from 1-60 seconds before crond acts on the changes.  crond also scans the per-user crontabs in /etc/cron.d and /var/spool/cron/crontabs automatically once per hour - this is 'hardcoded' and can't be changed.  Because of how crond maintains an internal crontab structure, and fact that cron's are user-based, it's important to use the 'crontab' command to manage this, else very strange results can happen (such as seemingly removed cron entries still getting played).

**Comment by bergware** [comment]
Ah, thanks for the explanation, I did see indeed the file 'cron.update' appear.

The way the cron update is initiated now is by calling the script update_cron (see Wrappers.php). If you are working on an inotify approach then parse_cron_cfg needs to be updated.

**Pull request merged**
