### PR TITLE
New diagnostics utility

### PR DESCRIPTION
**Pull request by bergware**
Can you make a symlink to /usr/local/sbin for the diagnostics script (see scripts folder).

### CODE REVIEW

**Comment by limetech** [comment]
Sure I will do that.  After merge I'll also make a couple documentation changes, e.g., to define what is *not* copied (personal info such as passwords and ssh keys).

Wonder if you could add something similar: a "Backup Flash" utility that will simply zip up the entire flash device contents and save to a zip file to download?   Later we can figure out what a Restore might do.

**Comment by bergware** [comment]
I can make a Backup utility, but danger is that local zip file is created in RAM and may run out of space, depending on how much data is stored in flash.

**Comment by limetech** [comment]
Now that's what I'm talking about!!  Nice job, that's exactly what I envisioned.  A couple little glitches here and there but a great improvement.

**Comment by bergware** [comment]
Okay, let me know the glitches you observed and other remarks/changes and I "polish" further ...

**Comment by limetech** [comment]
On Device pages:

1. The ‘Download’ button doesn’t seem to work.  After clicking I just see a blank page.  Tried both chrome and firefox.  Not sure I like the placement of the button there, maybe it’s mostly useful in ‘tabbed’ (vs. ‘non-tabbed’) view?  I usually use just non-tabbed view.   Maybe would be better to put the button under Device settings and what it does is download result of ‘smartctl -a’.

2. With array Stopped, the Next/Previous shows a blank page when you advance to an un-configured device (a slot that has no device assigned, ie, DISK_NP status).

3. In non-tabbed view would be nice maybe to have the Next/Previous buttons on all the page headers.

5. In the Attribues/Capabilities/Identify pages the table heading for column 1 is the Disk number instead of a description of what is being displayed in column 1.  I guess you did it like this so that when hitting Prev/Next in tabbed view you know which disk you’re on?  But maybe the way to solve this is, on Device settings tab include which which disk it is: “Disk 1 Device Settings” or “Device Disk 1 Settings” or just “Disk 1 Settings”.

On Shares page:

6. When array is not started, the tabs should not show up at all, instead just display “Array must be Started to view Shares”.  This can be put into the Shares.page and add Cond that array must be started in ShareList and DeviceList pages.  This will avoid having two warnings show up in non-tabbed view.

On Device Shares page:

7. Should call them “Disk shares”, not “Device shares” – to be consistent with other documentation.

8. There should only be one ‘Cache’ share even if there are multiple cache devices.

9. The ‘compute…’ function does not work.

10. Would be nice to Next/Prev buttons for shares too :)

**Pull request closed without merging**
