### PR TITLE
Fix: Save/Test settings on Notification Agents page

### PR DESCRIPTION
**Pull request by eschultz**

### CODE REVIEW

**Comment by bergware** [comment]
Eric,

Is this in response to a specific issue given in the forum?

**Comment by eschultz** [comment]
We've gotten a couple bug reports directly and this forum post is related: https://lime-technology.com/forum/index.php?topic=46567.0

I was able to confirm the issue in both Firefox and Chrome.  I think the sole issue is quoting the attribute value when it contains square brackets from:
`input[name=#arg\\[1\\]]`
to:
`input[name="#arg\\[1\\]"]`

Maybe related to the new version of jQuery?

**Comment by bergware** [comment]
I didn't see anything in the jquery release notes related to this, but it is good practice anyway to quote the value.

**Comment by eschultz** [comment]
It's difficult to tell the commit log between 2.1.4 and 2.2.0 is massive!  It was probably a simple regex tweak that resulted in better selector performance and didn't fail any of the unit tests so it was approved :)

Oh, and jQuery 2.2.1 is out now.

**Pull request merged**
