### PR TITLE
webGUI funtionality enhancements

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by eschultz** [comment]
Ronald, good call on the Windows logo!  I'll update the one in VM Manager, somehow we have the Windows Vista logo in-place for Windows 7 item.  

Hopefully we haven't triggered PTSD with our Windows Vista logo exposure :fearful:

**Comment by limetech** [comment]
Nice idea with history logs!

**Comment by limetech** [comment]
What do you mean by this?

"Note: at the moment SMART settings are merged, it can be considered to
make these standard in the arrays "Disks" and "var"."

**Comment by bergware** [comment]
I have created the script "CustomMerge.php" which reads two separate files "smart-all.cfg" and "smart-one.cfg" and merges their content (if existing) with the arrays "disks" and "var".

Instead of separate files these entries may be put part of the arrays themselves, but it requires you to extend the current assignment of the arrays. It is for consideration not an absolute must have.

**Pull request merged**
