### PR TITLE
Create Container Revamp

### PR DESCRIPTION
**Pull request by gfjardim**
Guys, these are the modifications I proposed to you. 

The major change is in the XML schema; what I did was consolidate Environment,Networking and Data elements into one element ( **Config** ) and add support for Devices.

This allowed the inclusion of some attributes:
**Type**, with the type of the setting (Port, Path, Device or Variable);
**Title**,  with the name of the setting;
**Default**, with the default value, allowing user to Reset the setting;
**Target**, with the container side of the setting, e.g. /config for a path or USERNAME for a variable;
**Description**, with the description of the setting;
**Mode**, applicable to Port (tcp/udp) and Path (rw/ro).
**Display**, that can be always, advanced or hidden, and will only be visible if the correspondent toggle is on.
**Required**, that will block the form submit if empty;
**Mask**, that will hide passwords if selected.

I used jQuery heavily, so most of the data is loaded from a Settings variable exported by the PHP code; the initial config is done by the `<script>` tag in the end of the file.

I added a Dry Run button only visible when Advanced is selected, that will allow users to preview the output of XML and the CLI command.

I designed the new xml schema to be backward-compliant with the old schema; what differentiate both is a version="2" on the `<Container>` element on the new schema.

Thanks a lot for your support.

### CODE REVIEW

**Comment by gfjardim** [comment]
The update status is kind of broken in the current code. I have a fix ready, but I'll wait to commit, since some changes are useful even if this code is rejected.

**Comment by eschultz** [comment]
...just finished reviewing the code.  Looks good to me and seems a bit cleaner as well.  Pushing these changes on a test system locally and will have our crack team of QA testers (Jon) beat it up and see if he finds any issues.

and sticking with your headers:
```
#   ███╗   ██╗██╗ ██████╗███████╗    ██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗██╗
#   ████╗  ██║██║██╔════╝██╔════╝    ██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝██║
#   ██╔██╗ ██║██║██║     █████╗      ██║ █╗ ██║██║   ██║██████╔╝█████╔╝ ██║
#   ██║╚██╗██║██║██║     ██╔══╝      ██║███╗██║██║   ██║██╔══██╗██╔═██╗ ╚═╝
#   ██║ ╚████║██║╚██████╗███████╗    ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗██╗
#   ╚═╝  ╚═══╝╚═╝ ╚═════╝╚══════╝     ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
```

**Comment by gfjardim** [comment]
I knew you would like those ASCII arts! 

Tell Jon I made my BTSync and CrashPlan templates compatible with this.

**Comment by limetech** [comment]
We're just about to release 6.1-rc3 so we will wait until after that to merge your work (which is very nice btw).  One of the changes in this release is that we are enforcing a command "jail".  That is, use of the 'cmd=xxx' or '#command=xxx' query variables can only reference executables in /usr/local/emhttp/...  Specifically not /usr/local/sbin or any other path.  For example, places where #command is set to "/usr/bin/docker" have been replaced with "/usr/local/emhttp/plugins/dynamix.docker.manager/docker" where the latter is a wrapper script that invokes /usr/bin/docker.  This will become more obvious once we publish -rc3.  Sorry for the extra work this might cause but we need to close this security hole.

**Comment by gfjardim** [comment]
We can remove the shell usage if you like, Tom, and use Docker socket and json instead to create containers.

I just maintained the use of shell and cli to be transparent to users and keep it because in early stages was all about shell commands.

**Comment by limetech** [comment]
Yes that would be great!

**Comment by bergware** [comment]
Have been playing around with the new *style* and I like the simplification. I do have a few recommendations which you may want to consider

1. For the popup windows include the *default-white.css* stylesheet, this allows the content to be displayed using the same font and button style as used elsewhere in the GUI

2. In version 6.1 control of the buttons is performed by Dynamix, this requires the buttons to be labeled *Apply* and *Done*. When a user changes an input field then the *Apply* buttons changes into *Reset* and this won't require the individual Reset buttons which are currently present.

3. All Help text is displayed in bold, I would change that to normal font as it is done for all other help pages.

4. Something to consider for the future: current implementation is repository-centric, I propose to move to an application-centric approach, as is done with the Community Applications plugin, this however involves more than GUI changes.

Thanks, keep up the great work :)

**Comment by gfjardim** [comment]
Tom, I'll commit some modifications, like start/stop/restart using json. Docker creation will took more time, as I have to decipher the JSON format and see what is needed and what isn't. 

Bergware,

1) I'll take a look into it;
2) It's not a "Reset to prior state", it's a "Use default value", the default value that exist on the template xml. I'll rename it to "Default".
3) It's a CSS thing; I'll fix it.
4) I' do agree, but it's a thing for the future. My plan is to simplify things first, then add Community Applications into Dynamix.

**Comment by KodeStar** [comment]
@gfjardim your shell execs for starting/stopping/creating dockers don't utilise #command=xxx so it shouldn't be an issue should it?

**Comment by gfjardim** [comment]
Hi @KodeStar. It used to be a #command=xxx, but now it's a post command submitted to a parser that controls containers and images using Docker API.

**Comment by jonpanozzo** [comment]
Thank you for your patience on this @gfjardim.  Wanted to provide you an update on where things stand with this pull request and our intentions at this point, as we had a team meeting earlier today to review this for inclusion in unRAID OS 6.2.  Here's what we intend to do:

**We are adding two new configurable options to the Docker Settings page:  default config path and default data path.**
The default config path will be a user-configurable option that will universally map to /config from within any container where /config is specified as a volume mapping.  The default setting for this in the webGui itself will be to map the default config path to /mnt/user/appdata/$appname, where the $appname is taken from the "name" field of a given container.  This means that container authors that specify a /config volume mapping will not need to put anything in their XML to define the host side of that mapping anymore.

The default data path will create a volume mapping from within the container called /unraid which, by default, will map to /mnt/user.  The user will be able to override the host path from within the Settings -> Docker Settings page.

For each individual container, the path fields for /config and /unraid will not be displayed by default, but by turning on "Advanced View", the user will be able to edit and/or remove these mappings on a per-container basis.

**We are tweaking the Add Container page a bit**
The plan is to get rid of the multiple "sections" on this page and have only one toggle for advanced/basic view.  

*Basic view*:
* *Name* will be hidden.
* *Network type* will be hidden.
* The default config and data path fields will be hidden.
* All port mappings will be hidden.
* *All volume mappings specified in the template XML will be displayed*

The last one is important.  Let's take for example the container CAdvisor, which has numerous additional volume mappings including:

/rootfs -> /
/var/run -> /var/run
/sys -> /sys
/var/lib/docker -> /var/lib/docker

Those mappings will be displayed, because they are asking for the user to give the container access to non-default paths.

*Advanced View*
All fields will be visible.

**But what about this pull request?**
Because of the changes we have made in 6.1, this request is currently unable to be merged, so the plan is that @eschultz will be manually incorporating your code (e.g. copy/paste) and fixing where necessary to both accommodate the design changes detailed here as well as the security changes required to be compliant with unRAID 6.1.  We won't be able to merge this request as is, but will leave it open until Eric's work is complete.

**Summary**
This is being worked on right now, and when complete, a beta of 6.2 will be sent to you for previewing.  Words cannot properly express our gratitude for your work here and on the wiki to document the new XML schema.  This is simply AWESOME and we're very excited to incorporate these changes in unRAID OS.

**Comment by gfjardim** [comment]
Thanks for your exposition, Jonathan. As I said before, it's a proposition to make things more fluid to users.

Thanks a lot for your consideration.

**Comment by jonpanozzo** [comment]
Most definitely.  The changes you made are for the better, so we look forward to incorporating them in 6.2.  Thanks again!

**Comment by eschultz** [comment]
Thanks again @gfjardim !
This was merged in to https://github.com/limetech/dynamix-6.2

**Pull request closed without merging**
