### PR TITLE
webGUI general update

### PR DESCRIPTION
**Pull request by bergware**
All
- Updated copyright 2014 to copyright 2015
- "Done" button changes
to "Reset" after user modifies a field
- "Default" button makes instant
changes (read and apply default.cfg file)
- Move javascript files to
their own folder (except for VM manager)

Dynamix
- Removed option
"Uncommitted changes protection", defaults to YES
- Removed option
"Allow individual disk spin up/down", defaults to YES
- Removed option
"Show section icons", defaults to YES
- Proper file naming in styles
folder
- Add drag-n-drop feature to user images
- Updated Add Share and
Add User to work with new Done button behavior

### CODE REVIEW

**Comment by eschultz** [comment]
I like the clean up and re-organization you've done here, Ronald!  I'm concerned this will brake a few plugins out there (community apps comes to mind).  I know our policy is we technically don't support 3rd party plugins but we should come up with a plan to minimize disruption while still progressing unRAID development.

There's really two issues:
1)  When we roll out the next release with these changes many plugins will be broken until those authors release an update
2)  Anyone running 6.0 or an earlier beta running plugins should be prevented from getting a plugin update made for 6.0.1's structure changes

For 1, what if we added in a few symlinks from the old files to new files (any files moved from this pull request) just for the next release.  This would give authors a small window to test and roll out an update.  We'd remove those symlinks in a future version (e.g. 6.0.2).

For 2, is there a min version attribute we can use in the plugin xml?  This one is kind of minor because we'd like users to upgrade to 6.0.1, but I can understand if they want to wait a little bit after each release to see if it causes issues for other users.

I'm open to other suggestions or thoughts! :+1:

**Comment by bergware** [comment]
Yeah, risk is that some plugins may get broken (actually Community Apps is broken for its reference to dockerclient.php). Symlinking as an intermediate solution sounds feasible, would need plugin developers to check and modify their version, but may lead to incompatibility if plugin and webGUI are out of sync.

We should start thinking about a version control, which alllow plugins to check but also allows unRAID to reject, i.e. do not load the plugin. Need to give this more thoughts...

**Comment by bergware** [comment]
What is your preference change "Done" to "Reset" or change to "Cancel" ?

**Comment by limetech** [comment]
Whooo boy this is a monster!

FYI it's not really necessary to change the copyright year, even if you make a change in a later year.  If you wanted to though, it's better to specify both years or a range of years, eg:

Copyright 2004, Joe Programmer
becomes:
Copyright 2004, 2005 Joe Programmer
or
Copyright 2004-2005 Joe Programmer
in above case if Joe made a change in 2006 he would just change to
Copyright 2004-2006 Joe Programmer

But this really makes no difference - in US at least, all works are copyrighted "by default" even if no explicit notice is there and it really doesn't matter the year.

Nevertheless the gnu guys have their own recommendation:
https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

**Comment by bergware** [comment]
There needs to be a reason to call it version 6.1 :)

**Pull request merged**
