### PR TITLE
New diagnostics utility

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
Do you plan to merge this, or something I need to change  (as it stands now the merge is for apcups only).

**Comment by limetech** [comment]
Sure, I just didn’t have a chance to test yet.  I’ll merge it now.

 

Cheers,

Tom

**Comment by limetech** [comment]
BTW I am probably going to "catch hell" from people who think this is a "new feature" that shouldn't go into an -RC release.  I'm used to it...

**Comment by bergware** [comment]
apcupsd, is not really new. Though its appearance has changed (for the good I hope).

What are your thoughts on the diagnostics utility, which I took out for the moment, do you like to incorporate this in unRAID or leave it as a separate (optional) plugin ?

And yeah, there will be always complaints, no matter what you do ;)

**Pull request merged**
