### PR TITLE
Docker 1.7 and asset reorganization fixes

### PR DESCRIPTION
**Pull request by eschultz**

### CODE REVIEW

**Comment by bergware** [comment]
ROFL

I guess VM was a bit too virtual for me :)

**Comment by bergware** [comment]
Btw that image comes from a match I try to forget ...

**Comment by limetech** [comment]
LOL, Eric has slapped me with a few RED cards, and Jon is serving 6-month ban for biting :)

**Comment by bergware** [comment]
Did think, I saw a familiar face ...

suarez

**Pull request merged**
