### PR TITLE
Fixed days calculation of last parity check

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
The problem occurs when you make multiple changes. Try the following (with your code):

Select "banner1" and Apply -> this will change both the banner and the preview.

Select "banner2" and Apply -> this will update the banner but not the preview

The "hack" ensures the preview is also updated.

**Comment by limetech** [comment]
How about this: once someone defines a custom thumbnail/banner, they have to delete it first and then they can define a new one.

**Comment by bergware** [comment]
That won't require the "hack" but might be more cumbersome for the user (read: less intuitive).

**Comment by limetech** [comment]
Not a big fan of hacks like that.  The issue has to do with browser-side caching right?  I'm not really sure why that hack works.  Browsers seem to make a distinction between clicking 'Refresh' button vs. F5 key refresh.  Apparently reloading the page like that does an F5 style refresh but the reload done as a result of update.htm or update.php if different?  Why is that?

IMHO it's better to do this:
- if no custom image, use your text "Drag-n-drop a PNG file or click the image at the left"
- if custom image defined, "Click the trash can to restore default image"

In the Help text we can say, "To change custom image, first restore the default image and then specify a new image." - something like that.

**Comment by bergware** [comment]
The refresh after update.htm / update.php is done from cached information of the browser and is not the same as the forced reload refresh which bypasses/updates the browser cache.

I did some more testing but your scenario isn't going to work. The browser at some point caches the picture (both banner and preview) and consequently shows old ones.

Do this scenario:

1. Select banner1 and click Apply -> Done
2. Go back to display settings
3. Click the trashcan to restore default banner
4. Click Apply -> Done
5. Go back to display settings
6. Select banner2 and click Apply -> Done

At this point the browser will show banner1 (which is cached) and *not* banner2. This happens because we use the same file name but change its contents, which "confuses" the browser.

The forced reload solution (I don't really see it as a hack) overcomes this situation. I haven't found another way to ensure the correct picture display all the time without a forced reload.

**Comment by limetech** [comment]
Here is a way to do it without storing intermediate state in a cookie (aka, hack):

In DisplaySettings.page, in function upload(), add a call to new function forceReload() like this:

```
function forceReload() {
  window.onload = parent.location.reload(true);
}
function upload(remove) {
  // gets invoked when the user clicks APPLY, at this point image will be saved or deleted
  if (remove || filename=='reset') {
    $.post("/webGui/include/FileUpload.php",{cmd:'delete',filename:filename,path:path,output:"banner"});
  }
  else if (filename) {
    $.post("/webGui/include/FileUpload.php",{cmd:'save',filename:filename,path:path,output:"banner"});
    window.onload = forceReload();
  }
}
```
There is already a window.onload function defined by update.htm.  What this does is override that function with a bigger hammer.

**Comment by bergware** [comment]
Excellent, really smart thinking !

Made an update for both banner and user images.

**Pull request merged**
