### PR TITLE
Fixed bug in monitor script, miscounting active disks

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by jonpanozzo** [comment]
Does this solely have to do with the dashboard display page?

**Comment by jonpanozzo** [comment]
ignore previous comment, i think this fix is related to this post you made:

http://lime-technology.com/forum/index.php?topic=38387.msg356580#msg356580

**Comment by bergware** [comment]
yeah correct, it is a fix for notifications.

Is there a dashboard issue ?

**Comment by jonpanozzo** [comment]
No issue.  I just misread what you were stating.

**Pull request merged**
