### PR TITLE
Fixed Create Container page from overriding the theme to white.

### PR DESCRIPTION
**Pull request by eschultz**
Eliminated redundant redundant css/js includes.

### CODE REVIEW

**Comment by bergware** [comment]
I believe you can also remove the reference to the "font-awesome.min.css", it isn't used anymore.

**Comment by eschultz** [comment]
It's actually still being used for the Advanced Mode toggle on the AddContainer.page and UpdateContainer.page pages.

I'm really liking the Font-Awesome library and it's used heavily on the Docker Containers page.  In a future release we might even switch-out some of the disk status icons to Font-Awesome icons.  On a HiDPI screen the crispness/quality stands out.

I don't want to replace the page/section icons, but we should replaced them with 32x32 (or higher) versions and specify width:16px and height:16px for the img element.  This will keep them the same size but increase (double) their DPI making them look better on HiDPI screens.

**Comment by bergware** [comment]
To improve readability of the header information when the logo is displayed, I propose the following changes:

default-white.css
#header .block{margin:10px 5px 0 0;float:right;text-align:right;background-color:rgba(255, 255, 255, 0.4);border-radius:10px;padding:2px 8px;}

default-black.css
#header.image{background:url(../images/banner.png) no-repeat #000000;border-radius:5px;color:#D0D0D0;}
#header .block{margin:10px 5px 0 0;float:right;text-align:right;background-color:rgba(0, 0, 0, 0.4);border-radius:10px;padding:2px 8px;}

@Eric, can you include these in your pull request, thx.

**Comment by bergware** [comment]
See you have updated the jquery and jqueryUI versions too, good job.

On my server I have been running these versions for a while already without issues, just to confirm that things work fine (people need to clear their browser cache first, though).

**Comment by eric** [comment]
Wrong eric.

**Comment by eschultz** [comment]
@bergware Yeah, I've been using the latest jQuery + UI for several weeks and all was well too.  To bust up the caching we could append `?20150208` or some other unique query string to the dynamix.js script src and other related css files.  Browsers will think they're new files not in cache and the server won't mind the query string when serving those static files.

@eric Power to the Erics! :fist:

**Pull request merged**
