### PR TITLE
Update jQuery to version 2.2.0

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by eschultz** [comment]
Cool, I had this on my list to upgrade soon.  I'd imagine this jQuery version would just be a 'drop-in' and work just fine with our existing code.

**Comment by bergware** [comment]
Yeah, a simple find and replace. No issues found so far.

**Comment by limetech** [comment]
Speaking of issues - did you have a chance to try out the 6.1.8 pre-release I sent?  Seems to me there shouldn't be any issues jumping from PHP 5.4.x to 5.6.x, but wondering what your thoughts are on that...

**Comment by bergware** [comment]
I have tested the pre-release and haven't found any issues with PHP 5.6.

As an extra measure I've read the release notes of PHP5.5/5.6 and didn't find any compatibility issues either.

**Comment by limetech** [comment]
Great!  Thanks for the review.  I will merge this PR as well as the final frontier PR.  In addition there's yet another PHP 5.6 patch release now (5.6.18), and I'll update dmidecode package.  Finally, I'll release this publicly as "6.1.8", but note, please delete your 6.1.8 'pre-release' since it won't actually be the 'official' 6.1.8 :)

**Comment by bergware** [comment]
I'll wait for the final release *to boldly go where no man has gone before...*

**Pull request merged**
