### PR TITLE
Enhancements to diagnostics utility

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by limetech** [comment]
bergware: wondering if you could make one more change to this before we merge the PR: in the zip file replace with 'array' folder with 'vars' and create inside it 'vars.txt' which captures the entire set of GLOBAL's in the same way Vars.page does?

**Comment by bergware** [comment]
Since diagnostics runs as an independent script, it requires all variable to be read (similar to what template.php is doing). Is this what you want?

**Comment by bergware** [comment]
Diagnostics now reads all available /var/local/emhttp/*.ini files and stores their content in ./system/vars.txt

**Comment by bergware** [comment]
One caution though: the user registration info is included as well (GUID + name).

Filter or what ?

**Comment by bergware** [comment]
Hmm, i filtered the registration and flash info part, but other personal info are the user names ...

**Comment by bergware** [comment]
I am working on plugging all the security holes in dockers (there are more than initially thought)

Will pull a update later today.

**Comment by eschultz** [comment]
I started working on Docker and VM code to work with security updates in update.php, I wonder if I can merge some of my work in to this pull request...

I see from your commits that you've gone down the same route I had regarding the free-for-all text input to checkbox, LOL:
`<input type="checkbox" name="#arg[4]" value="-r">`

**Comment by bergware** [comment]
I did as much as possible to avoid regression, but need more eyes to scrutinize the docker changes.

**Comment by bergware** [comment]
The basic idea as discussed before is still there, but when applying the changes to the docker part, I found a "swiss cheese" ... The culprit is *Exec.php* which allows execution of any command. In an effort the straighten things (read: remove full paths and perform secured command execution) I needed to adjust several files. E.g. docker start/stop didn't follow the security concept, hence some javascript changes as well.

@Eric: you might want to work upon my changes, if you don't mind.

**Comment by bergware** [comment]
Hmm, I do see my changes conflict with the proposals  of gfjardim. We need to align that!

**Comment by bergware** [comment]
Sorry, a bit too enthusiastic from my side. Copied too much of my own habits.

**Pull request closed without merging**
