### PR TITLE
Replace leading zero with leading space in date search (parity-check history)

### PR DESCRIPTION
**Pull request by bergware**
Not sure if I am in the lead with those zeroes and spaces ...

### CODE REVIEW

**Comment by bergware** [comment]
Have a look at the approach I have taken to allow independent webGUI updates.

Within the dynamix.plg file I have introduced a new variable "unRAID" which denotes the version of unRAID which goes along with the webGUI.

Only changing the webGUI version results in an update available for the webGUI.

Changing both "version" and "unRAID" will suppress the new webGUI update, used when a new version itself is issued as well.

**Comment by bergware** [comment]
Have a look at the color coding stuff which I have added lately. Let me know what you think.

Might be interesting to do a merge :)

**Comment by bergware** [comment]
Ok, another interesting update.

Long tables are now dynamically shortened based on screen size. This prevents long scrolling and the header stays visible all the time. Have a look at e.g. syslog, vars and processes.

Did the same trick for the tables holding plugins, dockers and VMs.

**Comment by bergware** [comment]
Note to add:

I moved the global disk temperature and disk utilization settings under the Disk Settings page, but keep those settings stored in their original variables/files. To do this a "dispatch" function is called when the form in the Disk Settings page is submitted.

**Comment by bergware** [comment]
This is Ground Control to Major Tom

Can you hear me, Major Tom?
Can you hear me, Major Tom?

Planet Earth is blue
And there’s nothing I can do.

**Comment by eschultz** [comment]
tom_major
Thanks Ronald!

**Comment by bergware** [comment]
heheh :)

Tranquility Base here...., the Eagle has landed

**Pull request merged**
