### PR TITLE
Device pages and Share pages enhancements

### PR DESCRIPTION
**Pull request by bergware**
Device pages:

1. Fixed download button
2. Fixed N/P when array is stopped
3. Page headers have N/P buttons in non-tabbed view
4. Disk name is displayed in title bar, tables have applicable headers

Shares pages
1. Renamed to "Disk Shares"
2. Fixed a single cache share only in case of cache pool
3. You need to make the script "disk_size" executable
4. Share have N/P buttons too

And a few more enhancements ...

1. Protection against missing "menu" item
2. New "Png" attribute to select an icon file instead of auto-selection
3. Removed unnecessary conditions
4. CSS correction

### CODE REVIEW

**Comment by limetech** [comment]
Question: does github strip off the 'executable' bit?  For example, if 'disk_size' script is executable in your repo, why is it not executable here?

Couple more things to change:

Let's keep the 'Flash' SMB-export settings on the Flash device page.  The usb boot flash is treated specially:
* when enabled for export, the 'flash' share is available whether array started or not
* it's only accessible via SMB
* it doesn't support spinup/down, or SMART

Because of this I think it's ok to leave 'flash' off the DiskList.page table.

Normally when a Parity device is not present, the "Parity" device link is not present.  But if you click say Disk 1 link then click "Previous" you get the parity device page - that's a bug.

If you change Shares.page from this:
```
Menu="Tasks:2"
Type="xmenu"
Cond="($var['shareUser']=='e')"
```
to
```
Menu="Tasks:2"
Type="xmenu"
---
if ($var['fsState']!="Started") {
  echo "<p class='notice'>Array must be <strong><big>started</big></strong> to view Shares.</p>";
  return;
}
```
(And take array started test out of ShareList.page and DiskList.page but add
```
Cond="($var['shareUser']=='e')"
```
to preamble of ShareList.page.)

Then it will fix bug where disk shares not displayed if user shares are not enabled, and also present a better looking notice if array not started.

Finally: I would just make these simple changes myself, but here's another question for you:  If I make this kind of "organizational" change there will be those on the forum who will object because we are in the "-rc" phase of the 6.0 release, and such a change should be in say 6.1.  Personally, I would put it in because it improves the product.. what do you think?

**Comment by bergware** [comment]
I believe Windows is the culprit when it comes to attribute bits. My mode of operation is that I edit the files on a Windows machine (which is unaware of Linux attributes), and copy them over to my unRAID flash drive - at this point all attributes 'rwx' are automatically added. Next when I telnet into unRAID and make an internal copy from flash to final destination, it will be with all bits set.

Copying the Windows files to github however is without the attribute bits. I'll do some searching to see if it possible to include those bits from Windows, but not really hopeful.

I'll do the corrections as you propose, but feel free to change anything yourself.

Personally, I see these changes as enhancements in navigating the GUI, not really new functionality. And I must say it really simplifies accessibility to the share settings. For one I found myself that my share settings were not as consistent as I thought they would, and in the new layout it was a breeze to compare and change that.

I would say go ahead; yes some people will complain and mention -rc status, but surely most people will embrace the new layout, it does make life a lot easier!

**Comment by bergware** [comment]
Ok, corrections and enhancements are put on github.

1. Needed to expand the condition statement for User Shares and Disk Shares to check for the array running or not.

2. Flash SMB settings is no longer under Disk Shares but moved back to original under Flash.

3. Adjusted the disk "not present" status and included now parity too

4. Made enhancement in page loading time by retrieving all smartctl in background

**Comment by eschultz** [comment]
@bergware I had a feeling you were on Windows but I could find our old conversions about Git a while back to confirm that.  I think this is how you would update Linux attributes from Windows on a Git file you're about to commit:
http://blog.lesc.se/2011/11/how-to-change-file-premissions-in-git.html

**Comment by bergware** [comment]
Yeah that link is useful, thanks.

**Comment by bergware** [comment]
Ok, have made the files executable, and made a pull request on github.

**Pull request merged**
