### PR TITLE
Updated status icons

### PR DESCRIPTION
**Pull request by bergware**
Did some refinements to the new status icons and associated css.

### CODE REVIEW

**Comment by bergware** [comment]
These are png images which do not support animation, anyway I don't like blinking for two reasons:
1. Some blinking means "attention" - as have a look there might be something wrong here!
2. The constant 'flickering' of all icons blinking simultaneously is unpleasant to my eye

With Dynamix v5 I introduced "dark" and "light" colored versions to show on and off conditions. This doesn't work well in the dark scheme, it is very hard to distingish. The alternative: use "grey" as off and introduce a different shape for "non-present" devices. So fars this has worked best.

For "blinking" read/yellow/blue currently a lighter icon is shown, though again might be hard to see the difference between on and off here (in reality the off condition hardly happens in these situations). Grey is an alternative but one would loose the non-normal condition.

The total icon was introduced to have it visually looking pleasant - all rows in the array start with an icon.

**Comment by bergware** [comment]
Of course 'my' icons are not set in stone, any good ideas I am open to it (make sure it works both in the white and black theme though).

**Comment by limetech** [comment]
It's all good man :)  My "LED" concept is also not set in stone, and yes the blinking can be annoying.

Actually I liked the square symbol used for a missing parity disk.  Maybe we should explore the idea of shapes a little more because it also solves the problem of how to accommodate color blindness.

One thing I like was the symbols in the icon rollover that indicates whether to spin a drive up or down (they look like a pair of chevrons pointing up or down).  At one time dynamix (or simple features?) displayed these next to the orbs - what if we brought those back?

**Comment by bergware** [comment]
Yeah another approach can be different shapes, like the red square for a wrong/missing parity disk. Will experiment here a bit.

I introduced the up/down symbols in SimpleFeatures at the time, and it was initially ported to Dynamix, but at the end I choose for a 'consistent' look and feel, that is a single status icon regardless of individual disks may or may not spin down/up.

The up/down symbol is now part of the popup message when moving the cursor over the status icon.

Another thought: a small up or down triangle, similar to what is used in sorting arrays ?

**Comment by bergware** [comment]
See also this discussion on the forum: http://lime-technology.com/forum/index.php?topic=38440.0

**Comment by bergware** [comment]
Your addition of the textarea class overrules the css styling in my change. In that respect they don't clash, but it makes my change ineffective though.

**Comment by bergware** [comment]
Tom,
Can you explain what is holding you off to merge the pull reuqest ? The list of changes is getting quite long now, and some fixes are essential, e.g. notifications.

Let me know how you want to proceed. Thx.

**Comment by limetech** [comment]
Yes. There is now a merge conflict that I need to work out.  Also, we really didn't want to go through the exercise of changing all the indicators at this time.  That is because, imho, this is not critical to getting unRaid-6.0 to 'rc' or even 'final' release.  In addition we are in process of generating screen shots for various documentation purposes and some of these will need to be re-done - again something I didn't want to spend time on now.  Anyway I will work on the merge but hopefully in the future we can have smaller pull requests instead of bundling everything in a single large pull.

**Comment by bergware** [comment]
Don't know if there is an easy way to 'undo' certain pull requests from my side (like the revised icons).

If there is (or you know off) and it makes your life easier, I will do.

For some reason my different pull requests all end-up under the same pull, not sure what is causing the bundling of all these, certainly is not my intended way.

**Comment by limetech** [comment]
No worries, almost got it.

**Comment by bergware** [comment]
I have removed the conflicting parts, and adopted to the changes made by Eric.

**Comment by limetech** [comment]
Have to say: very nice work!

**Comment by bergware** [comment]
You may want to change the status icons back to original ... :)

**Comment by limetech** [comment]
No I'm liking the status icons.  Don't really like the 'totals'/'slots' icon (the blue orb with a plus symbol); change it to a blank and see if you like that better.  If we keep the icons alongside devices only then it's easy to tell at a glance in the normal case that everything is good: all you see is GREEN ;)

**Comment by bergware** [comment]
If you want I change it back to the "old" green plus icon

**Comment by limetech** [comment]
How about no icon at all - just blank space?

**Pull request merged**
