### PR TITLE
Enhanced diagnostics utility

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by eschultz** [comment]
Ronald, could you please also include these additional logs:
- /var/log/docker.log
- /var/log/libvirt/libvirtd.log   (*The main libvirt log*)
- /var/log/libvirt/qemu/\*.log  (*The log for each VM*)

Jon and I discussed this a couple days ago and thought including them would be helpful.  Thanks!

**Comment by bergware** [comment]
Eric,
New version available with log files as you've indicated.

docker.log and libvirtd.log are stored together with syslog in the subfolder "logs"
qemu log files are stored in the new subfolder "qemu" (an 'empty' message is made if no log files)

**Comment by bergware** [comment]
Always fun those "special" characters.... correction made!

**Comment by eschultz** [comment]
Looks great, Thanks Ronald! :cake:

**Pull request merged**
