### PR TITLE
Develop/features/docker.manager.refresh

### PR DESCRIPTION
**Pull request by eschultz**
A few _minor_ changes to Docker Manager and some core file :bowtie:

### CODE REVIEW

**Comment by limetech** [comment]
Outstanding!  Wonder what a *major* update would look like :)

**Comment by jonpanozzo** [comment]
That would be domain manager 😉.






Sent from Windows Mail





From: tom mortensen
Sent: ‎Saturday‎, ‎February‎ ‎7‎, ‎2015 ‎12‎:‎40‎ ‎AM
To: limetech/dynamix





Outstanding! Wonder what a major update would look like :)

**Comment by bergware** [comment]
Great improvement. Using Docker looks less daunting now!

A few first observations which require your attention ...

1. When enabling the docker apps display on the dashboard, it will stop updating all the other tables on the boardboard

2. Press "add container" brings up a page which doesn't adhere the color theme selection (it uses always the white theme)

3. There is a checkbox in the top-right corner of the Docker page without any label. Perhaps it belongs to "Log" but then it is positioned too high (I am using Chrome)

4. I miss the pop-up feature when pressing the application icon, how to get now into webGui of the app?

**Comment by gfjardim** [comment]
This is awesome piece of work, Eric, congratulations and then you!

The Advanced Mode works very well. I will investigate if it’s possible to eliminate those base images too, leaving only the truly orphaned images there.

One thing I miss is the multiple containers operation. Maybe something like this (http://datatables.net/examples/api/select_row.html <http://datatables.net/examples/api/select_row.html>) can provide a seamlessly option, maintaining the awesome layout you made!

And that’s it. I was worrying about this revamp when the first images came out, but now I’m officially impressed!

Again, congratulations!

Guilherme Fichtner
gfjardim@gmail.com



> Em 07/02/2015, à(s) 01:16, Eric Schultz <notifications@github.com> escreveu:
> 
> A few minor changes to Docker Manager and some core file 
>

**Comment by eschultz** [comment]
Thanks everyone for the compliments and feedback.  I can easily fix the Add Container page color theme bug, it's a trivial patch.

**Pull request merged**
