### PR TITLE
Correction in file size detection of image upload

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
I haven't tested the true boundaries of a POST request and the 50K/200K is more of an artificial restriction. Personally I like to see files not bigger as they should be, but this might hurt unknowing people.

You can raise the limit to a higher value (need to adjust the warning text then as well), and as a precaution test with a large file to confirm it is accepted.

**Comment by limetech** [comment]
Yes I tested up to 600kB.  Also, I totally agree with keeping file size down, which is why I specified the recommended image dimensions in the Help text.  But it would be quite frustrating for user to constantly use some kind of tool to reduce images size.  Space on flash for larger images is negligible and once image is cached on browser-side, bandwidth is negligible too, therefore it's better to create a good experience for the user and let them upload larger files if they want without any hassles.

**Comment by bergware** [comment]
Totally understandable that for a user experience a higher limit works better...

I've changed the limit to 600kB, see pull request

**Comment by limetech** [comment]
Do you notice any buggy behavior with thumbnail upload?  I'm still seeing this:

If either dragging or manual selection, image would appear it's actual size in the browser.  Apply button does get enabled but then clicking Apply had no effect - that is, the image was not uploaded.

capture

Tried this using IE/FF/Chrome all with same effect.  Very strange.

**Comment by bergware** [comment]
Any chance sending that picture and I can test?

I try a "big" picture here and it is resized to 48x48 as should (using Chrome)

**Comment by bergware** [comment]
Never mind, download another "dock" picture and have the same result as you.

Weird!

**Comment by bergware** [comment]
Also browsers don't like pictures with 32-bit (or 24-bit) color depth, they only accept 8-bit depth.

**Comment by limetech** [comment]
Below is the image, but it happens with several.  I *think* if the image size 48x48 is works every time.  If I manually copy the below file to /boot/config/plugins/dynamix/users it seems to always display correctly regardless of bit depth.  Also you can take a jpg and rename it with a png extension and that works too
emmett

**Comment by bergware** [comment]
Something in the upload function prevents the file sending to the server when it is 32-bits.

I need to check that ...

**Comment by limetech** [comment]
That's extremely odd isn't it?

**Comment by bergware** [comment]
I fixed the display issue (needed to set size 48x48 explicitely)

I've done some testing with different file sizes and color depths. My testing shows that files up to 96KB are accepted, which due to base64 coding is 128KB for the actual transfer, going bigger than that and the file isn't transferred.

I don't know if this a browser limitation (different browsers all act the same) or a server limitation.

**Comment by limetech** [comment]
Ok I guess until we figure out where the 128K limit is coming from I'll go ahead and set 96kB as the max file size to upload.  Thanks for looking into this.

BTW at present emhttp max post content is 2MB but that's arbitrary and easily changeable.  I'm hoping eventually we can use the file upload code to permit user to upload and install a release zip file, but those things are 70MB+.

**Pull request merged**
