### PR TITLE
Disable "collect" button while diagnostics is running

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by jonpanozzo** [comment]
Also, should we relabel that to “Download” instead of “Collect”?  Collect just sounds a little confusing compared to how we do this for the syslog / other features.

**Comment by bergware** [comment]
But everywhere we are talking about *collection*, *collecting* or *collected* ...

Shouldn't the button simply not follow that notion?

**Comment by jonpanozzo** [comment]
Well, I guess my thought is that the action the user is taking when they click that button ultimately results in them downloading a zip file containing their diagnostics.  The collection process happens in the background and is transparent from the user’s perspective.  I’m not opposed to leaving it as-is, just thought I’d bring it up since it’s always kind been in the back of my mind.

**Comment by bergware** [comment]
True at the end it is a single file which is downloaded, the reason I called it *collect* was to differentiate between a single file download (e.g. syslog) and the gathering of different parts of information. This *should* give the user a better understanding of what is happening. Though at the end it might be only semantics ...

**Comment by jonpanozzo** [comment]
Like I said, not opposed to leaving it as-is.  It’s really not a big deal.  Just thought it was odd because it’s the only place in the webGui where we have a button that says “collect” but we have other places we just say “download”.  It’s really not even worth the amount of time we’ve spent discussing it ;-).

**Comment by bergware** [comment]
No worries Jon :)

I was just reading some comment from RobJ on the new diagnostics. Some commands were added and updating the text in the GUI should be done.

Don't know what you guys think of the disk file naming under SMART reports? I added the "ata" postfix to have a quick reference between syslog messages and the actual drive.

**Comment by limetech** [comment]
Please change it to "Download" because download specifically means to bring a file down to the PC on which the browser is running.  Some people will see "collect" and wonder, "what are they collecting" - meaning maybe we are collecting information and sending it to LimeTech as well as downloading a file.

Much more consistent to use "Download" and then in the Help section you can say something like:

"This operation simply collects relevant system configuration and logging information and places it in a zip file that is downloaded.  No information is sent to any server."

**Comment by bergware** [comment]
Since this function is rather delicate, can I propose you do the textual changes. It will ensure the text will satisfy your needs/wishes.

**Comment by limetech** [comment]
Sure.

**Pull request merged**
