### PR TITLE
Add status popup to user/disk/flash shares

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
Withdraw this one, replaced by LT implementation

**Comment by limetech** [comment]
Ok, my changes require a new release because I also fixed some logic in emhttp.  I am generating a new release now called -rc4a which I'll email to you and then push the dynamix changes.

**Comment by bergware** [comment]
ok, I have correction which you need to include. Will send an email with the file.

**Comment by limetech** [comment]
ok

**Comment by bergware** [comment]
The change in the file I just sent is very small, the first line becomes:

`Menu="Disk Share Flash"  ==> Menu="Disk Share"`

**Pull request closed without merging**
